mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py
mpirun python3 linear_reg.py